---
- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot_required
  register: reboot_required
  when: ansible_facts["distribution"] == "Debian"

- name: Reboot device
  become: true
  ansible.builtin.reboot:
    reboot_timeout: "{{ reboot_timeout }}"
  when: reboot_required is defined
