---
- name: raspi-config | Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ config_hostname }}"
- name: raspi-config | Set Raspberry locale
  become: true
  ansible.builtin.command:
    cmd: raspi-config nonint do_change_locale {{ config_locale }}
  changed_when: true
