---
- name: services | Disable interfaces
  become: true
  ansible.builtin.command:
    cmd: raspi-config nonint "{{ item }}" 1
  changed_when: true
  loop: "{{ config_disable_interfaces }}"
- name: services | Get service information
  ansible.builtin.service_facts:
- name: services | Disable services
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ config_disable_services }}"
  when: item in services
- name: services | Disable bluetooth in boot configuration
  become: true
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    insertafter: EOF
    line: dtoverlay=disable-bt
    regexp: "^#*\\s*dtoverlay=.*$"
- name: services | Purge packages
  become: true
  ansible.builtin.apt:
    name: "{{ config_purge_packages }}"
    purge: true
    state: absent
