---
- name: ufw | Install package
  become: true
  ansible.builtin.package:
    name: ufw
    state: present
- name: ufw | Whitelist ports
  become: true
  ansible.builtin.command:
    cmd: ufw allow {{ security_allow_ufw_ports | join(',') }}
  changed_when: true
- name: ufw | Enable
  become: true
  ansible.builtin.command:
    cmd: ufw --force enable
  changed_when: true
