---
- name: ufw | Install package
  become: true
  ansible.builtin.package:
    name: ufw
    state: present
- name: ufw | Whitelist ports (UDP)
  become: true
  ansible.builtin.command:
    cmd: ufw allow {{ security_allow_ufw_ports_udp | join(',') }}/udp
  changed_when: true
- name: ufw | Whitelist ports (TCP)
  become: true
  ansible.builtin.command:
    cmd: ufw allow {{ security_allow_ufw_ports_tcp | join(',') }}/tcp
  changed_when: true
- name: ufw | Enable
  become: true
  ansible.builtin.command:
    cmd: ufw --force enable
  changed_when: true
